### PR TITLE
Update to Guzzle ~6.0

### PR DESCRIPTION
**Pull request by jessedc**
Quick changes I made to update to Guzzle ~6, feel free to close if you'd prefer to keep ~5 as Guzzle 6 requires PHP 5.5+.

The the exception of incompatible PHP 5.4, the failing tests are fixed in #3

### CODE REVIEW

**Comment by Maks3w** [comment]
Is it possible to remove guzzle dependency and only relay on PSR7 Interfaces?

**Comment by jessedc** [comment]
Yes, good idea.

**Comment by Maks3w** [comment]
@jessedc Take a look to current master and tell me if works for you

**Comment by jessedc** [comment]
Excellent. That's what I was thinking - a new assertion trait for PSR7. Very nice providing the backwards Compatibility.

**Pull request closed without merging**
