### PR TITLE
Allow uppercase characters in request query parameters

### PR DESCRIPTION
**Pull request by roelywoely**

### CODE REVIEW

**Comment by Maks3w** [comment]
Test please

**Comment by roelywoely** [comment]
Done.

**Comment by Maks3w** [comment]
Because query string is case insensitive the only way for validate is normalize.

I recommend you to use lower case in your swagger definition.

**Comment by waldbaerkoch** [comment]
Hi

> Because query string is case insensitive the only way for validate is normalize.

Is it?

RFC 3986 does not define the `query` part (https://tools.ietf.org/html/rfc3986#section-3.4) to be case-insensitive, whereas is does for the `scheme` and `host` parts.

And

> 6.2.2.1.  Case Normalization
>  When a URI uses components of the generic syntax, the component syntax equivalence rules always apply; namely, that the scheme and host are case-insensitive and therefore should be normalized to lowercase.  For example, the URI <HTTP://www.EXAMPLE.com/> is equivalent to <http://www.example.com/>.  The other generic syntax components are assumed to be **case-sensitive** unless specifically defined otherwise by the scheme (see Section 6.2.3).

https://tools.ietf.org/html/rfc7230#section-2.7.1 and https://tools.ietf.org/html/rfc7230#section-2.7.2 defining the `http` and `https` URI schemes do not override this.

Or do you mean the query parameters in Swagger?

https://swagger.io/specification/#parameterObject:
> Parameter Object
> ...
> name string REQUIRED. The name of the parameter. Parameter names are **case sensitive**.

https://swagger.io/specification/v2/#parameterObject:
> name string Required. The name of the parameter. Parameter names are **case sensitive**.

(highlighting is mine)

Looks like query **is case-sensitive** and so the lower-casing is wrong.

**Pull request closed without merging**
